### ISSUE TITLE
Переписать разделы

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/docs_ngmobile#11]
Разделы по созданию полигона. мультиточки, мультилинии и мультипорлигона расписать по аналогии с разделами создание точки и линии.
Лишние слова убрать, лишние или дублирующиеся рисунки убрать.

**Comment by baryshnikova131076** [comment]
http://docs.nextgis.ru/docs_ngmobile/source/editing.html#id5

http://docs.nextgis.ru/docs_ngmobile/source/editing.html#id6

http://docs.nextgis.ru/docs_ngmobile/source/editing.html#id7

http://docs.nextgis.ru/docs_ngmobile/source/editing.html#id8
