### ISSUE TITLE
Написать как попасть в режим редактирования

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/docs_ngmobile#15]
В документации по редактированию есть todo: куда надо написать как собственно попасть в этот режим. А то как в режиме работать написано, а каким образом в него попасть - нет.

**Comment by simgislab** [comment]
чуть добавил https://github.com/nextgis/docs_ngmobile/commit/e555705a32cfa56c19f2027d2a9942f51e0ca28f

и в общем было уже описано
