### ISSUE TITLE
Описать создание нового слоя

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/docs_ngmobile#18]
В раздел про загрузку (http://docs.nextgis.ru/docs_ngmobile/source/load_geodata.html) добавить про создание новго слоя. Сам раздел переименовать в Добавление слоев. Добавить пометку к новомук подрезделу про создание нового слоя, что это новое в версии 2.3 (тег пишется вот так: http://www.sphinx-doc.org/en/stable/markup/para.html#directive-versionadded)

**Comment by hawkedw** [comment]
Добавить тоже самое в раздел 3.3.1.

**Comment by simgislab** [comment]
то что @BishopGIS написал - было сделано
