### ISSUE TITLE
Актуализовать до версии 2.4

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/docs_ngmobile#20]
@simgislab @4eRTuk 
Можете сюда кинуть ссылку или дать описание изменений в НГМ.

**Comment by simgislab** [comment]
Вот что имхо важно было бы отразить в доках
- [x] Новый диалог загрузки данных из NGW (Add from NextGIS)
- [x] Новый диалог свойств слоя (разбиение по вкладкам настроек)
- [x] Добавление сервисов QMS (Add geoservice)
- [x] Переработанная панель редактирования объектов
- [x] Инструмент измерения площади и длины
- [x] Линейка масштаба
- [x] Добавление новых слоев из ЗИПованных geojson
- [x] Undo/Redo в процессе редактирования объекта
- [x] Задание цвета для каждого трека

Вот [тут](http://ether.gis-lab.info/JUX9dgDPly) еще есть подробности (в первой части).
