### ISSUE TITLE
Заполнение стандартной формы редактирования атрибутов

### ISSUE THREAD

**Issue by simgislab** [nextgis/docs_ngmobile#31]
Не понял о чём это:

> Особенностью редактирования векторного слоя, полученного при загрузке файла формата GeoJSON, является заполнение стандартной формы редактирования атрибутов. Такая стандартная форма содержит следующие поля:

Вот тут: http://docs.nextgis.com/docs_ngmobile/source/load_geodata.html#geojson

**Comment by BishopGIS** [comment]
По моему все понятно. Если загружаешь geojson, то его можно редактировать **только** через стандартную форму, которая поддерживает **только** 3 типа контролов ввода.

**Comment by simgislab** [comment]
переписал
