### ISSUE TITLE
Расписать про кастомные формы

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/docs_ngmobile#5]
У нас появился ряд контролов. Нужно сделать скриншот со всеми контролами и перечислить их в виде списка.

**Comment by baryshnikova131076** [comment]
Просьба предоставить форму со всеми контролами

**Comment by BishopGIS** [comment]
@simgislab, @trolleway, @MikhanGusev кто ни будь можете сделать такую форму, а то FB пока на линуксе нету.

**Comment by BishopGIS** [comment]
@simgislab, @trolleway, @MikhanGusev тикету уже 3 месяца - разве так сложно сделать?

**Comment by simgislab** [comment]
Форма со всеми контролами

![](http://m-d.me/img/ss/20160104-203-191kb.jpg)

Скачать ngfp можно здесь: https://www.dropbox.com/s/68e9hn63o8hb0uq/form-all-controls.ngfp?dl=0

Закройте если это то - что нужно было.

**Comment by BishopGIS** [comment]
Сделано
